# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY server.py .

# Install dependencies
RUN pip install --no-cache-dir .

# Set the entrypoint to run the MCP server
ENTRYPOINT ["python", "server.py"]
