[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "podbean-mcp"
version = "0.1.0"
description = "MCP server for Podbean API"
dependencies = [
    "mcp>=1.7.1",
]
